### ISSUE TITLE
Trending section should be scrollable

### ISSUE THREAD

**Issue by Nathan-Somto** [victorcodess/flixify#2]
Great project ! You really got the design.

One enhancement i feel that can be made is making the trending section scrollable.  because it has like 5 movies but the user can't see them because it is hidden and not scrollable.

**Comment by victorcodess** [comment]
Hi Nathan, thanks for the feedback. 
I'm not sure if you tried, but there's a horizontal scroll on the trending section. Have you tried doing that?
